def text_io_exceptions_fn():
    print("TEXT IO EXCEPTIONS RESULTS:")
    # TODO: test these
